version: "3"
services:
    workspace:
        image: golang:1.15
        volumes:
            - ./workspace/:/opt/workspace:cached
            - ./go/:/go:cached
        ports:
            - 8080:8080
        working_dir: /opt/workspace
        environment:
            PORT: 8080
        command: bash
        tty: true